---
title: 'PPOL561 | Reading List'
date: 'Spring 2021'
output: 
  html_document:
    css: style.css
    theme: spacelab
    highlight: default
    toc_depth: 3
    toc: true
    toc_collapsed: true
    toc_float: true
---

### [Home](../index.html)


### Week 1: Course Introduction & Research Design

- **_Required Readings_**:

  - Please review course syllabus. 
  
- **_Suggested Reading_**:
  
  - King, G., Keohane, R.O. and Verba, S., 1994. "Designing social inquiry: Scientific inference in qualitative research." _Princeton university press_.

  
### Week 2: Data wrangling in R

- **_Required Readings_**:
    
  - Grolemund & Wickham. 2017. "R for Data Science".
      
      + [Ch. 10: Tibbles](https://r4ds.had.co.nz/tibbles.html)
      + [Ch. 12: Tidy Data](https://r4ds.had.co.nz/tidy-data.html) 
      + [Ch. 15: Dates and Times](https://r4ds.had.co.nz/dates-and-times.html) 
      + [Ch. 5: Data Transformation](https://r4ds.had.co.nz/transform.html) 
      + [Ch. 18: Pipes](https://r4ds.had.co.nz/pipes.html) 
      + [Ch. 3: Data Visualization](https://r4ds.had.co.nz/data-visualisation.html)
      + [Ch. 7: Exploratory Data Analysis](https://r4ds.had.co.nz/exploratory-data-analysis.html)
      
- **_Suggested Reading_**:

  - [Data Types and Structures](https://swcarpentry.github.io/r-novice-inflammation/13-supp-data-structures/index.html) - Software Carpentry
  
  - Grolemund & Wickham. 2017. "R for Data Science".
  
      + [Ch. 20: Vectors](https://r4ds.had.co.nz/vectors.html) 
      + [Ch. 21: Iteration](https://r4ds.had.co.nz/iteration.html) 
      + [Ch. 19: Functions](https://r4ds.had.co.nz/functions.html)
      + [Ch. 14: Strings](https://r4ds.had.co.nz/strings.html)
      + [Ch. 11: Import Data](https://r4ds.had.co.nz/data-import.html)
      + [Ch. 27: R Markdown](https://r4ds.had.co.nz/r-markdown.html)
      + [Ch. 8: Workflow: Projects](https://r4ds.had.co.nz/workflow-projects.html)


### Week 3: Introduction to Causal Inference

- **_Required Readings_**:
  
  - Cunningham. 2018. "Causal Inference: The Mixtape".
      
      + Chapter 4: "Directed Acyclical Graphs" (Canvas)
          
      + Chapter 5: "Potential Outcomes Causal Model" (Canvas)
      
      
### Week 4: OLS, Confounders, & Simulation

- **_Required Readings_**:
  
  - Bailey. 2016. "Real Stats: Using Econometrics for Political Science and Public Policy".
    
      + Refresh on Chapters. 5 - 7
      
  - Schrodt. 2014. "Seven deadly sins of contemporary quantitative political analysis".
  
    
### Week 5: Panel Data & Difference-in-Difference

- **_Required Readings_**:

  - Bailey. 2016. "Real Stats: Using Econometrics for Political Science and Public Policy".
    
      + Chapter 8
      
      
### Week 6: Instrumental Variables

- **_Required Readings_**:

  - Bailey. 2016. "Real Stats: Using Econometrics for Political Science and Public Policy".
    
      + Chapter 9
      
      
### Week 7: Experiments

- **_Required Readings_**:

  - Bailey. 2016. "Real Stats: Using Econometrics for Political Science and Public Policy".
    
      + Chapter 10
      
### Week 8: Regression Discontinuity

- **_Required Readings_**:

  - Bailey. 2016. "Real Stats: Using Econometrics for Political Science and Public Policy".
    
      + Chapter 11
      
### Week 10: Matching

- **_Required Readings_**:
  
  - Ho et. al 2007 (Canvas)
  
- **_Suggested Reading_**:
  
  - King and Neilson 2018 (Canvas)
  - Austin 2010 (Canvas)  
  - matchit.pdf (Canvas)

### Week 11: Synthetic Control

- **_Required Readings_**:

  - Cunningham. 2018. "Causal Inference: The Mixtape".
      
      + Chapter 11: "Synthetic Control" (Canvas)
      
- **_Suggested Reading_**:
  
  - Abadie et al. 2010, "Synthetic Control Methods for Comparative Case Studies: Estimating the Effect of California’s Tobacco Control Program" (Canvas)
  - Abadie et al. 2015, "Comparative Politics and the Synthetic Control Method" (Canvas)
      

### Week 12: Binary Outcomes

- **_Required Readings_**:
  
  - Bailey. 2016. "Real Stats: Using Econometrics for Political Science and Public Policy".
    
      + Refresh on Chapter 12
      
  - Hanmer and Kalkan. 2013. "Behind the Curve: Clarifying the Best Approach to Calculating Predicted Probabilities and Marginal Effects from Limited Dependent Variable Models"
      
- **_Suggested Reading_**:

  - Long. 1997. "Regression models for categorical and limited dependent variables".
    
      + Chapter 3 (Canvas)
      
      
### Week 13: Ordered & Multinomial Outcomes

- **_Required Readings_**:
  
  - Read Lecture Summary handouts:
    
      - Ordered Outcomes (Canvas)
      
      - Multinomial Outcomes (Canvas)
    
- **_Suggested Reading_**:

  - Long. 1997. "Regression models for categorical and limited dependent variables".
    
      + Chapter 5 & 6 (Canvas)
      
### Week 14: Selection

- **_Required Readings_**:

  - Bailey. Draft Chapter. "Selection" (Canvas)
  
  - Wooldridge. "Introductory Econometrics". Pg. 627 - 633. (Canvas)
  
- **_Suggested Reading_**:

  - Berinsky, Adam. 1999. “The Two Faces of Public Opinion” American Journal of Political Science 43: 1209-1230.
  
  - Lemke, Douglas and William Reed. 2001. “War and Rivalry among Great Powers” American Journal of Political Science 45: 457-469.
  
  
